/* AgriGuardian i18n: translation strings */
var LANG = {
  en: {
    appTag: "Defending against cyber predators",
    navDash: "Dashboard", navDevices: "Devices", navAdd: "Add device",
    totalDevices: "Total devices", actNow: "Act now", actionSoon: "Action soon",
    highPriority: "Highest priority", allDevices: "All devices",
    addDevice: "+ Add a device", addTitle: "Add a device",
    brand: "Brand", selectBrand: "Select a brand...", deviceType: "Device type",
    selectType: "Select a type...", deviceLabel: "Device name or label",
    labelPlaceholder: "e.g. North field sensor #3", optional: "(optional)",
    pwChanged: "Has the default password been changed?",
    addBtn: "Add device and check risk",
    lookingGood: "Looking good", takeAction: "Take action soon", actNowBadge: "Act now",
    backBtn: "Back to devices",
    detailBrand: "Brand", detailType: "Device type", detailPw: "Default password changed",
    detailSupport: "Manufacturer support", detailCve: "Known vulnerabilities",
    detailAutoUpdate: "Auto-update", detailFirmware: "Last device software update",
    pwYesVal: "Yes", pwNoVal: "No / not sure", cveFound: "found", cveNone: "None on record",
    resolveNoteLabel: "Optional: add a note about what was done...",
    resolveWarning: "Never enter usernames, passwords, or login credentials in this field.",
    lookingGoodMsg: "This device appears secure.",
    tapVerify: "Tap below to verify it is still secure.",
    monitorMsg: "Continue to monitor and re-evaluate if anything changes.",
    resolvedBadge: "Marked resolved:",
    healthStatus: "Verification status",
    healthOpts: ["🟢 Updates automatically","🟡 I update it myself","🔴 No updates available for this device"],
    healthTitle: "Device software updates",
    healthNotes: "Verification notes (optional)",
    healthNotePlaceholder: "e.g. Software updated by dealer on June 2026",
    healthWarning: "Never enter usernames, passwords, or login credentials here.",
    saveHealthBtn: "Save verification",
    healthStamp: "Last verified:",
    alertMsg1: "device requires immediate attention.",
    alertMsgN: "devices require immediate attention.",
    loginTitle: "Welcome to AgriGuardian", loginSub: "Defending against cyber predators",
    loginPhone: "Phone number", loginCode: "Verification code",
    loginSend: "Send code", loginVerify: "Verify & sign in", loginRole: "Your role",
    loginRoles: ["Owner","Manager","Technician","Farm Hand","Viewer"],
    loginFarm: "Farm name",
    loginName: "Your name",
    loginEmailOpt: "(optional — for reports)",
    loginRegTitle: "Create your account",
    loginRegSend: "Send verification code",
    loginWelcomeTitle: "Welcome",
    loginWelcomeSub: "Are you a new user or returning?",
    loginCreateBtn: "Create an account",
    loginSigninBtn: "Sign in to existing account",
    loginSigninTitle: "Sign in",
    loginSigninSub: "Enter the phone number you registered with.",
    loginVerifyTitle: "Verify your number",
    loginBack: "Back",
    lockoutMsg: "Too many failed attempts. Please wait {n} seconds before trying again.",
    lockoutBanner: "Account temporarily locked. Please wait",
    lockoutSeconds: "seconds.",
    lockoutMinutes: "minutes.",
    forgotPassword: "Forgot password?",
    resetTitle: "Reset password",
    resetSub: "Enter your phone number and we'll send a reset code.",
    resetPhone: "Your phone number",
    resetSendBtn: "Send reset code",
    resetCodeLabel: "Verification code",
    resetNewPw: "New password",
    resetConfirmBtn: "Set new password",
    resetSuccess: "Password updated successfully! Please sign in with your new password.",
    attemptsRemaining: "attempt remaining",
    attemptsRemainingPlural: "attempts remaining",
    loginLockoutNote: "In production, lockout is enforced server-side and tied to the account — a page refresh will not reset it.",
    editMemberTitle: "Edit member",
    saveChangesBtn: "Save changes",
    auditLogTitle: "Audit Log",
    noAuditActivity: "No activity recorded yet.",
    auditShowingLast: "Showing last",
    auditAction: "action",
    auditActions: "actions",
    productionSecTitle: "Production security",
    encHead: "Data encryption:",
    backupHead: "Backup strategy:",
    archHead: "Architecture:",
    perfHead: "Performance:",
    encryptionNote: "All data encrypted in transit (TLS) and at rest (AES-256) in production.",
    backupNote: "Automated daily backups with 30-day retention planned for production.",
    architectureNote: "Core features in base app. Advanced analytics offered as optional add-ons.",
    performanceNote: "App evaluated for load time and database efficiency at each release milestone.",
    loginFarmTz: "Farm time zone",
    aboutLabel: "About",
    accessibilityLabel: "Accessibility",
    addNetworkConn: "Add a network connection",
    addNetworkBtn: "Add network connection",
    addDeviceBtn: "+ Add device",
    addADevice: "Add a device",
    addANetwork: "Add a network connection",
    brandLabel: "Brand",
    selectBrand: "Select a brand...",
    otherNotListed: "Other / Not listed",
    mfrModelNum: "Manufacturer model number",
    usedForLookups: "(used for security lookups)",
    usedForVulnLookups: "(used for vulnerability lookups)",
    deviceNameLabel: "Device name or label",
    selectLocation: "Select a location...",
    addCustomLocation: "+ Add custom location...",
    selectConnType: "Select connection type...",
    selectType: "Select type...",
    hasPwChanged: "Has the default password been changed?",
    isEncrypted: "Is this network encrypted?",
    yesEncrypted: "Yes (WPA2/WPA3 or equivalent)",
    routerBrand: "Router / modem brand",
    selectBrandNet: "Select brand...",
    modelNumLabel: "Model number",
    uniqueTypeNote: "Device type names must be unique (not case-sensitive).",
    uniqueRoleNote: "Role names must be unique (not case-sensitive).",
    uniqueBrandNote: "Brand names must be unique (e.g. John Deere and johndeer would be considered the same).",
    enterBrandPlaceholder: "Enter brand name",
    modelPlaceholder: "e.g. JD4066R, ValleyX",
    serialPlaceholder: "e.g. SN-2024-88471",
    enterTypePlaceholder: "Enter device type",
    deviceLabelPlaceholder: "e.g. North field sensor #3",
    customLocationPlaceholder: "e.g. Bumblebee Field, Lower 40, Back Barn",
    dealerPlaceholder: "e.g. Dealer: Ag Supply Co — John Smith 555-2341",
    netNamePlaceholder: "e.g. Farm Wi-Fi, Barn router, Field sensor network",
    netModelPlaceholder: "e.g. Netgear Nighthawk R7000, Cisco RV340",
    memberNamePlaceholder: "e.g. Sarah Tully",
    customRolePlaceholder: "Enter custom role name",
    cameraType: "Camera / security",
    sessionTitle5min: "5 minutes (demo)",
    sessionTitle15min: "15 minutes",
    sessionTitle30min: "30 minutes",
    sessionTitle1hr: "1 hour",
    sessionShortNote: "Shorter timeout recommended for shared or field devices.",
    onOffOff: "Off",
    onOffOn: "On",
    nvdLabel: "NVD — National Vulnerability Database",
    nvdDesc: "NVD provides detailed CVE records searchable by model number. In production, AgriGuardian would connect to NVD through a secure backend server — the API key would never be exposed to the browser.",
    nvdArchNote: "The NVD API key lives on AgriGuardian's server. The app sends a request to the server, the server calls NVD, and returns results — the key never touches the browser. This is standard practice for protecting API credentials in web applications.",
    prodArchLabel: "Production architecture:",
    allRightsLabel: "All rights reserved.",
    protoLabel: "Prototype — Alpha version",
    createdByLabel: "Created by",
    addTeamMemberTitle: "Add a team member",
    farmTimezoneLabel: "Farm time zone",
    assignRoleLabel: "Assign role",
    addNewRoleOption: "+ Add new role...",
    sortByLabel: "Sort by:",
    farmAccountHeader: "Farm account",
    teamMembersHeader: "Team members",
    timezoneHeader: "Farm time zone",
    sessionHeader: "Session settings",
    workerDetails: "Enter the worker's details. They will receive an SMS invitation to download AgriGuardian and join your farm account.",
    memberFullName: "Full name",
    selectTeamMember: "Select a team member...",
    whatWasDone: "What was done?",
    notesHeader: "Notes",
    riskLevelSort: "Risk level",
    netRiskWhyNoPw: "Default password has not been changed — a common attack vector.",
    netRiskWhyNoEnc: "This connection is not encrypted — data may be interceptable.",
    netRiskWhyGood: "This connection appears secure. Continue monitoring.",
    noteJohnDeere: "Cloud-based authentication via Operations Center. MFA available and recommended.",
    noteValley: "Older panel controllers may use default credentials. Cloud portal (Valley 365) supports MFA.",
    noteHogSlat: "Local web UI with weak authentication. No MFA available. Default passwords are publicly documented.",
    noteDeLaval: "Barn controllers often use default credentials. Local login only on older units with no remote update path.",
    noteTrimble: "Cloud account with MFA available. Keep field devices updated via the Trimble portal.",
    noteDJI: "MFA available via DJI account. App-based authentication is secure when properly set up.",
    noteArable: "Cloud-centric device. No local login. MFA supported on the Arable portal.",
    noteOther: "Device not in our database. Apply general security guidance and contact the manufacturer directly.",
    riskWhyNoPw: "The default password has not been changed — a publicly known vulnerability that attackers actively scan for.",
    riskWhyCve: "This device brand has {n} known security vulnerabilities recorded in public databases.",
    riskWhyCve1: "This device brand has {n} known security vulnerability recorded in public databases. Confirm it has been patched.",
    riskWhyLimited: "Manufacturer support is limited, meaning security patches may not be issued for new vulnerabilities.",
    riskWhyUnknown: "This device is not in our database. We recommend applying general security guidance.",
    describeWhatDone: "Describe what was done...",
    verifyDeviceSecure: "Verify this device is still secure",
    verifyAgain: "Verify again",
    verifyStaleNote: "It's been a while since this was checked. Last verified:",
    optional: "(optional)",
    brandSort: "Brand",
    nameSort: "Name",
    locationSort: "Location",
    addNetworkBtnShort: "+ Add network",
    connWifi: "Wi-Fi",
    connEthernet: "Ethernet (hardwired)",
    connCellular: "Cellular (LTE/5G)",
    connSatellite: "Satellite",
    connBluetooth: "Bluetooth",
    connLoRa: "LoRa",
    connUnknown: "Unknown",
    a11yColorBlindDesc: "Adds shapes alongside colors for risk levels",
    a11yDisableMotion: "Disables transitions and animations",
    a11yExtraLarge: "Extra large text",
    a11yExtraLargeDesc: "Maximum text size for low vision",
    a11yHighContrast: "High contrast",
    a11yHighContrastDesc: "Stronger contrast between text and backgrounds",
    a11yLargeText: "Large text",
    a11yLargeTextDesc: "Increases text size across the whole app",
    a11yReducedMotion: "Reduced motion",
    cisaLabel: "CISA Known Exploited Vulnerabilities",
    connectedLabel: "Connected",
    connTypeLabel: "Connection type",
    fullName: "Full name",
    issuesLabel: "Issues",
    nameOrLabel: "Name or label",
    networkConns: "Network connections",
    networksLabel: "Networks",
    passwordLabel: "Password",
    pendingBackend: "Pending backend integration",
    riskLevelLabel: "Risk level",
    sendMfa: "Send MFA code",
    timeZoneDesc: "Time zone used for all timestamps",
    verifyIdentity: "Verify your identity",
    vulnDatabases: "Vulnerability databases",
    locationNorthField: "North field",
    locationBarn: "Barn",
    locationPasture: "Pasture", locationSouthField: "South field",
    locationEastField: "East field", locationWestField: "West field",
    locationMainHouse: "Main house", locationGrainBins: "Grain bins",
    locationDairyBarn: "Dairy barn", locationMachineShed: "Machine shed",
    typeIrrigation: "Irrigation controller",
    typeNetGateway: "Network gateway",
    typeGPS: "GPS / guidance system",
    typeAutomation: "Automation controller",
    typeRoboticMilker: "Robotic milker",
    typeWeather: "Weather station",
    typeDrone: "Drone", typeLivestock: "Livestock monitor",
    typeSoil: "Soil sensor", typeFeed: "Feed system",
    typeBarnVent: "Barn ventilation controller",
    roleManager: "Manager", roleTechnician: "Technician",
    roleFarmHand: "Farm Hand", roleViewer: "Viewer",
    loginPassword: "Create a password",
    loginPassHint: "Password complexity rules will apply in production.",
    loginPassPlaceholder: "Min. 8 characters",
    loginDemoTitle: "How to explore this demo",
    loginDemoStep1: "Tap",
    loginDemoStep1b: "— fields are pre-filled for you.",
    loginDemoStep2: "Tap",
    loginDemoStep3: "Enter the demo code:",
    loginDemoStep4: "Tap",
    loginDemoStep4b: "to explore the app.",
    loginDemoCode: "Demo code: 123456",
    loginHaveInviteBtn: "I have an invite",
    loginDemoSubTitle: "Three ways in — pick one:",
    loginDemoCard1Title: "1. Create an account → Owner mode",
    loginDemoCard1Desc: "Walk through the full Owner setup. Fields are pre-filled. Verification code: 123456",
    loginDemoCard2Title: "2. Sign in → demo accounts already created",
    loginDemoCard2Desc: "Tap Sign in and pick a pre-made team member to see the app from their role's perspective. Verification code: 123456",
    loginDemoCard3Title: "3. I have an invite → join an existing farm",
    loginDemoCard3Desc: "Tap I have an invite and enter code 987654 to see how a new team member accepts a farm invitation. Registration is view-only.",
    loginLastUpdated: "Last updated:",
    loginOptionalReport: "(optional — for reports)",
    loginUsernameHint: "(this is your username)",
    loginVerificationSent: "A verification code was sent to your phone.",
    loginPhoneUsername: "Your phone number is your username.",
    loginNewOrReturning: "New user or returning?",
    loginVerifyBtn: "Verify & sign in",
    loginSendMfa: "Send MFA code",
    loginPasswordLabel: "Password",
    loginPhonePlaceholder: "(555) 000-0000",
    loginCodePlaceholder: "123456",
    loginYourPhone: "Your phone number",
    loginEmail: "Email",
    loginEmailPlaceholder: "you@example.com",
    loginEmailNote: "optional — for reports",
    settingsTitle: "Farm settings",
    farmInfo: "Farm account",
    teamTitle: "Team members",
    addMember: "Add a team member",
    memberPhone: "Phone number",
    memberRole: "Assign role",
    inviteBtn: "Invite",
    inviteNote: "The worker will receive an SMS with instructions to download AgriGuardian and join your farm account.",
    sessionTitle: "Session settings",
    timeoutLabel: "Auto sign-out after inactivity",
    timeoutNote: "Shorter timeout recommended for shared or field devices.",
    securityTitle: "Security",
    pwRulesLabel: "Password requirements",
    pwRulesText: "Password complexity rules will be enforced in production.",
    navSettings: "Settings",
    pwYes: "Yes, I changed it", pwNo: "No / not sure",
    detailPwYes: "Yes", detailPwNo: "No / not sure",
    resolveActions: ["Password changed","Device disconnected from network","Device replaced","Device software updated","MFA enabled","Monitoring the situation"],
    netActions: ["Password changed","Encryption enabled","Network segmented","Router replaced","Monitoring enabled"],
    otherLabel: "Other",
    locationLabel: "Location", connectionLabel: "Connection",
    modelLabel: "Model number", serialLabel: "Serial number",
    macLabel: "MAC address",
    macFieldLabel: "MAC address",
    macHint: "Helps tell apart two devices of the same model.",
    dealerLabel: "Dealer & contact info",
    hardwareBrand: "Hardware brand", hardwareModel: "Model number",
    netNotesLabel: "Notes", netAdditionalNotes: "Additional notes",
    hwVulnCheck: "Check for known vulnerabilities",
    resolvedOn: "Marked resolved:", verifiedOn: "Last verified:",
    noTeamMembers: "No team members found.",
    invitedStatus: "Invited", activeStatus: "Active", archivedStatus: "Archived",
    permAdd: "Add devices", permArchive: "Archive / delete devices",
    permResolve: "Resolve issues & update device health",
    permAssign: "Assign issues to team members",
    permExport: "Export & download reports",
    tlTitle: "Device history",
    tlAdded: "Device added to AgriGuardian",
    tlFlaggedHigh: "Flagged as high risk",
    tlFlaggedAttention: "Flagged — needs attention",
    tlAssigned: "Assigned to",
    tlHealthSet: "Update status recorded:",
    tlResolved: "Issue addressed",
    tlVerified: "Verified secure",
    assignTitle: "Assign this issue",
    assignDesc: "Make someone responsible for addressing this issue.",
    assignSelectPlaceholder: "Select a team member…",
    assignBtn: "Assign",
    reassignBtn: "Reassign",
    unassignBtn: "Clear assignment",
    assignedToLabel: "Assigned to",
    unassignedLabel: "Not yet assigned",
    assignNoteLabel: "Instructions / what to do",
    assignViewOnlyGroup: "View-only (instruction only)",
    assignViewOnlyHint: "View-only people can't resolve issues \u2014 your note is an instruction for them.",
    assignNotePresets: ["OK to keep using", "Check with management before proceeding", "Do not use until checked"],
    assignedInstructionLabel: "Instruction for you",
    assignNotePlaceholder: "What should this person check or fix?",
    noAssignableMembers: "No team members are available to assign. Add active team members in Settings first.",
    handoffNoteRequired: "A note is required for every handoff. Please describe what needs to be done.",
    handoffNoteLabel: "Note / what you're doing",
    handoffLogTitle: "Handoff history",
    handoffTypeAssign: "Assigned",
    handoffTypeEscalate: "Escalated",
    handoffTypeSendBack: "Sent back",
    handoffTypePartialFix: "Partial fix",
    handoffTypeResolved: "Fully resolved",
    handoffTypeTakeOwnership: "Took ownership",
    takeOwnershipNotePlaceholder: "What are you doing to address this? (e.g. contacting vendor, arranging replacement)",
    returnedBannerTitle: "Sent back with instructions",
    returnedBannerFrom: "From",
    returnedBannerHint: "Review the instructions above, then resolve or re-escalate if needed.",
    sendBackBtn: "Send back to tech",
    sendBackNoteLabel: "Instructions for the technician",
    sendBackNotePlaceholder: "What should they try, check, or do before escalating again?",
    sendBackConfirmBtn: "Send back with instructions",
    dashFarmStatus: "Farm status",
    dashDeviceProblems: "Device problems",
    dashNetworkProblems: "Network problems",
    dashAssignedWork: "Assigned work",
    dashUnassigned: "Unassigned — needs someone",
    dashMyWork: "My assigned work",
    returnedDashLabel: "Returned to technician",
    issuesSingular: "issue",
    issuesPlural: "issues",
    noIssues: "All clear",
    allGoodMsg: "Everything looks good. No issues found.",
    techNoWorkMsg: "No work assigned to you and no open unassigned issues right now.",
    partiallyResolvedBadge: "Partially resolved",
    partialEscBannerTitle: "Partially resolved — decision needed",
    partialEscWhatFixed: "What {name} already fixed",
    partialEscWhatRemains: "What still needs a decision",
    partialEscHandledBy: "Currently assigned to {name} — or step in below to take it yourself.",
    logViewedTab: "Viewed {tab} tab",
    logViewedDevice: "Viewed device — {device}",
    logViewedNetwork: "Viewed network — {network}",
    partialResolveTitle: "Fix what you can + escalate the rest",
    partialResolveDesc: "Use this when you can address part of the issue yourself (e.g. changed the password) but something else needs a Manager or Owner decision (e.g. end-of-life hardware). Both actions are recorded in one step.",
    partialFixNoteLabel: "What did you fix / what did you do?",
    partialFixNotePlaceholder: "e.g. Changed the default password. Device still needs replacing — manufacturer no longer issuing firmware updates.",
    partialFixNoteRequired: "Please describe what you fixed before submitting.",
    partialFixByLabel: "Fixed by",
    partialResolveBtn: "Fix my part & escalate to {target}",
    partialResolveStepPw: "Step 1 — Change the default password on this device first, then record what you did below.",
    partialDashLabel: "Partially resolved — needs decision",
    required: "required",
    viewOnlyIssueNote: "You have view-only access. Contact the farm owner to address or assign this issue.",
    permView: "Read-only access (overrides all above)",
    restoreBtn: "Restore", archiveBtn: "Archive",
    permissionsLabel: "Permissions",
    navNetwork: "Network",
    archive: "Archive", archiving: "Archive", delete: "Delete", restore: "Restore",
    archived: "Archived", active: "Active", allLabel: "All",
    permissions: "Permissions",
    defaultPwChanged: "Default password changed",
    manufacturerSupport: "Manufacturer support",
    knownVulnerabilities: "Known vulnerabilities",
    lastSoftwareUpdate: "Last device software update",
    notes: "Notes",
    additionalNotes: "Additional notes",
    sending: "Sending...",
    keySaved: "Key saved for this session.",
    backToNetwork: "Back to network connections",
    signedOutInactivity: "You were signed out due to inactivity.",
    verificationSentTo: "A verification code was sent to ",
    invitationSentTo: "Invitation sent to ",
    timeZoneUpdatedTo: "Time zone updated to ",
    permanentlyDelete: "Permanently delete ",
    enterBrandName: "Please enter a brand name.",
    enterDeviceType: "Please enter a device type.",
    enterPhone: "Please enter a phone number.",
    enterMemberName: "Please enter the team member's name.",
    enterVerification: "Please enter the verification code.",
    fillAllFields: "Please fill in all fields.",
    alreadyInvited: "This number has already been invited.",
    enterRoleName: "Please enter a name for the new role.",
    incorrectCode: "Incorrect code. For this demo use: 123456",
    archiveUserPrompt: "Why is this member being archived?",
    archiveNote: "A note is required. Their record and history will be kept.",
    archiveReason: "Archive reason:",
    archiveDeviceConfirm: "Archive this device? It will be hidden from your active dashboard but its history will be kept.",
    archiveNetConfirm: "Archive this network? It will be hidden but history kept.",
    restoreDeviceConfirm: "Restore this device?",
    deleteDeviceWarn: "WARNING: This device has existing records.\n\nDeleting it will permanently erase all its history, risk records, and notes.\n\nWe strongly recommend Archive instead.\n\nTap OK to permanently delete anyway.\nTap Cancel to go back.",
    deleteDeviceConfirm: "Permanently delete this device? This cannot be undone.",
    fixBtn: "Fix →",
    reviewBtn: "Review →",
    hygieneTitle: "Farm Hygiene Score",
    hygieneOutOf: "out of 100",
    hygienePassword: "Password hygiene",
    hygieneUpdate: "Update hygiene",
    hygieneNetwork: "Network hygiene",
    hygieneApps: "Apps hygiene",
    hygieneBackup: "Backup hygiene",
    navBackups: "Backups",
    backupScreenTitle: "3-2-1 Backup status",
    backup321Title: "Your 3 copies",
    backup321Copy1Label: "Copy 1 — Primary (on-farm)",
    backup321Copy2Label: "Copy 2 — Second format",
    backup321Copy3Label: "Copy 3 — Offsite",
    backup321Copy1Short: "Primary copy",
    backup321Copy2Short: "Second-format copy",
    backup321Copy3Short: "Offsite copy",
    backup321Copy1Placeholder: "e.g. Farm PC + Time Machine on external drive",
    backup321Copy2Placeholder: "e.g. Synology NAS in barn office, or Google Drive",
    backup321Copy3Placeholder: "e.g. Backblaze B2 cloud (auto-nightly), or drive kept at home",
    backup321Copy1Note: "Where your data lives day-to-day",
    backup321Copy2Note: "A different device or service from your primary",
    backup321Copy3Note: "Physically or geographically separate from the farm",
    backupHaveThisCopy: "We have this copy",
    backupLastVerified: "Last verified (backups tested)",
    backupUpdateTitle: "Update backup status",
    backupNotesPlaceholder: "e.g. Auto-backup runs nightly via Backblaze — tested restore March 2026",
    backupRiskWhyMissing: "Missing: {copies}. All three copies are needed for full 3-2-1 protection.",
    backupRiskWhyNeverVerified: "All three copies are set up but have never been verified — a backup you haven't tested may not restore correctly.",
    backupRiskWhyStale: "Backups haven't been verified in over 90 days — test a restore to confirm everything still works.",
    backupRiskWhyGood: "3-2-1 backup rule is in place and recently verified.",
    backupRecActionRed: "Set up the missing backup copies. Start with an external drive (Copy 2) and a cloud service like Backblaze (Copy 3).",
    backupRecActionNeverVerified: "All copies are set up — now test a restore. Try recovering one file from each backup to confirm it actually works.",
    backupRecActionStale: "Verify your backups by restoring a test file. Check that your offsite copy is current.",
    backupRecActionGood: "No action needed. Verify again in 90 days, and after any major data changes.",
    navApps: "Apps",
    backToApps: "Back to apps",
    appsTitle: "Apps the farm uses",
    addApp: "+ Add app",
    addAnApp: "Add an app",
    noAppsYet: "No apps added yet.",
    appNameLabel: "App or service name",
    appNamePlaceholder: "e.g. QuickBooks Online, Climate FieldView",
    appVendorLabel: "Vendor",
    appVendorPlaceholder: "e.g. Intuit, Bayer",
    appPurposeLabel: "What is it used for?",
    appPurposePlaceholder: "e.g. Farm accounting & payroll",
    appReviewedQuestion: "Has this app been security-reviewed?",
    appAccountOwnerLabel: "Account owner",
    appAccountOwnerPlaceholder: "e.g. Angus MacDonald",
    appRenewalLabel: "Renewal / cost",
    appRenewalPlaceholder: "e.g. $35/mo, renews Jan 2027",
    appMfaLabel: "Multi-factor authentication (MFA)",
    appMfaQuestion: "Is multi-factor authentication (MFA) enabled?",
    appPwManagerLabel: "Password manager",
    appPwManagerQuestion: "Is the password for this app stored in a password manager?",
    appPwManagerNamePlaceholder: "e.g. Bitwarden, 1Password",
    appPwManagerWarning: "⚠️ Only enter the name of the password manager used — never the password itself or your master password.",
    appPickerLabel: "Pick a common app, or choose Other",
    appPickerSelect: "Select an app...",
    appPickerOther: "Other / not listed",
    addAppBtn: "Add app",
    appDetailsTitle: "App details",
    appReviewedLabel: "Security reviewed",
    appLastReviewedLabel: "Last reviewed",
    appReviewBoxTitle: "Update review status",
    appFlagInsecureLabel: "Flag this app as insecure / needs attention",
    appNotePlaceholder: "e.g. Reviewed access permissions, removed unused integration",
    appRiskWhyFlagged: "This app has been flagged as insecure or needing attention.",
    appRiskWhyNeverReviewed: "This app has not yet had a security review.",
    appRiskWhyNoMfa: "Multi-factor authentication is not enabled on this app.",
    appRiskWhyStale: "This app hasn't been reviewed in over 6 months.",
    appRiskWhyGood: "This app has been reviewed recently and looks good.",
    appRecActionFlagged: "Review the flag note, address the concern, and update the review status once resolved.",
    appRecActionReview: "Review this app's account access, permissions, and password before marking it reviewed.",
    appRecActionNoMfa: "Enable multi-factor authentication (MFA) on this account as soon as possible.",
    appRecActionStale: "It's been over 6 months — do a quick check that access and permissions still look right.",
    appRecActionGood: "No action needed. Re-review periodically, especially after staff changes.",
    archiveAppConfirm: "Archive {name}? It will be hidden from your active list but its history will be kept.",
    deleteAppConfirm: "Permanently delete {name}? This cannot be undone.",
    deleteAppWarn: "WARNING: This app has existing review history.\n\nDeleting it will permanently erase that history.\n\nWe strongly recommend Archive instead.\n\nTap OK to permanently delete anyway.\nTap Cancel to go back.",
    pdfReportTitle: "Farm Cyber Hygiene Report",
    pdfYourFarm: "Your Farm",
    pdfGenerated: "Generated",
    pdfActionList: "Priority Action List",
    pdfNoActions: "No outstanding security actions. Everything looks good.",
    pdfDeviceInventory: "Device Inventory",
    pdfNetworks: "Network Connections",
    pdfDevice: "Device",
    pdfNetwork: "Network",
    pdfType: "Type",
    pdfPwChanged: "Password changed",
    pdfStatus: "Status",
    pdfHigh: "High risk",
    pdfMedium: "Needs attention",
    pdfLow: "Secure",
    pdfResolved: "Resolved",
    pdfYes: "Yes",
    pdfNo: "No",
    pdfDisclaimer: "Generated by AgriGuardian. This report reflects self-reported device information and known-vulnerability data at the time of generation. It is provided for hygiene tracking and is not a guarantee of security.",
    pdfPopupBlocked: "Please allow pop-ups for this site to download the report.",
    lblDownloadReport: "Download PDF",
    lblDownloadActivity: "Download PDF",
    lblEmailReport: "Email Report",
    lblEmailActivity: "Email Report",
    lblReportHygieneTitle: "Hygiene Report",
    lblReportActivityTitle: "Activity Log",
    emailRequired: "Please enter your email address to use this feature.",
    emailInvalid: "Please enter a valid email address.",
    viewOnlyBadge: "view only",
    inviteTitle: "Join a farm",
    inviteSub: "Enter your invite code to get started.",
    inviteCodeLabel: "Invite code",
    inviteCodePlaceholder: "e.g. 987654",
    inviteAccepted: "Code accepted — complete your profile below",
    inviteYourName: "Your name",
    inviteYourPhone: "Phone",
    inviteRoleLabel: "Your role",
    inviteReadonlyNote: "Name and phone were set by the farm owner and cannot be changed. Demo invite registrations are view-only.",
    inviteDemoHintTitle: "ⓘ Demo invite code",
    inviteDemoHint: "Use code 987654 to register. Then use \"Sign in\" to explore as Carlos or Jamie.",
    inviteJoinBtn: "Join Old McDonald's Farm",
    inviteContinueBtn: "Continue",
    inviteBackBtn: "Back",
    demoMembersTitle: "ⓘ Explore as a team member",
    demoMembersSub: "Tap a profile to sign in as a pre-made team member and see their perspective.",
    carlosDesc: "Manager · can assign, resolve, export reports",
    jamieDesc: "Farm hand · view only",
    inviteRoleManagerDesc: "Can assign issues, mark resolved, export reports",
    inviteRoleManager: "Manager",
    inviteRoleFarmhand: "Farm hand",
    inviteRoleFarmhandDesc: "View only — can see devices and issues",
    inviteManagerDesc: "Assign issues, mark resolved, export reports",
    inviteFarmhandDesc: "View only — see devices and issues",
    inviteFillName: "Please enter your name and phone number.",
    invitePickRole: "Please select a role.",
    inviteDemoNote: "Name and phone were set by the farm owner and cannot be changed. Demo invite registrations are view-only.",
    emailRequiredForSend: "No report email address on file. Please add one in Settings → Farm account.",
    emailReportNote: "Generated by AgriGuardian. Download the full PDF report for complete details.",
    saved: "Saved",
    ownerEmailLabel: "Report delivery email",
    ownerEmailHint: "Used when emailing hygiene and activity reports.",
    pdfActivityTitle: "Farm Activity Log",
    pdfWhen: "When",
    pdfWho: "Who",
    pdfWhat: "Action",
    pdfNoActivity: "No activity recorded yet.",
    pdfActivityDisclaimer: "Generated by AgriGuardian. This log records actions taken within the app — who did what, and when. It does not track personal device information.",
    staleVerifyBadge: "Not verified in 6+ months",
    ownerRole: "Owner",
    resolveIssuesPerm: "Resolve issues",
    onlyOwnerTimezone: "Only the farm Owner can change the time zone.",
    tzNote: "All timestamps in the app will reflect this time zone regardless of where you are viewing from.",
    cisaDesc: "Automatically checked — no setup required. CISA publishes actively exploited vulnerabilities that AgriGuardian checks against your device brands.",
    vulnDbTitle: "Vulnerability databases",
    cisaTitle: "CISA Known Exploited Vulnerabilities",
    loginNamePlaceholder: "e.g. Joy McKenzie",
    loginFarmPlaceholder: "e.g. McKenzie Farm",
    loginPassPlaceholderHint: "Min. 8 characters",
    loginSigninPassPlaceholder: "Your password",
    loginPhonePlaceholderHint: "(555) 000-0000",
    pwChangedYes: "Yes", pwChangedNo: "No / not sure",
    supportedLabel: "Supported", limitedLabel: "Limited", unknownLabel: "Unknown",
    cveFoundLabel: "found",
    signOut: "Sign out",
    signOutFull: "⏻ Sign out",
    recommendedAction: "Recommended action",
    recActionRed: "Disconnect this device from your network until the default password is changed and the device is secured. Contact your dealer for assistance.",
    recActionYellowNoPw: "Change this device's default password today. Check the manufacturer's website or contact your dealer for step-by-step instructions.",
    recActionYellow: "This device has active security alerts. Review the known vulnerabilities and make sure its software is up to date.",
    recActionGreen: "This device looks secure. Keep monitoring it and keep its software up to date.",
    pwmTitle: "Use a password manager",
    fdlTitle: "Find the default login",
    fdlIntro: "This device may still use the login it shipped with. Find it, sign in once, and change it to a strong, unique password.",
    fdlLabelTitle: "Check the device itself",
    fdlLabelBody: "Many have a sticker on the bottom or back with the default login.",
    fdlManualTitle: "Check the manual or quick-start guide",
    fdlManualBody: "Look up the default login on the maker's support site for",
    fdlDealerTitle: "Ask your dealer",
    fdlDealerOnFile: "On file:",
    fdlWarning: "Change it right away. A default login is public knowledge and the top way devices get compromised.",
    pwmIntro: "This device still uses its default password. A password manager creates and remembers a strong, unique password for it, so you don't have to.",
    pwmNeverStores: "AgriGuardian never sees or stores your passwords. Keep them in the manager, not here.",
    pwmTrustedOptions: "Trusted options",
    pwmFreeTag: "Free",
    pwmVisit: "Visit",
    pwmDisclaimer: "Suggestions only. AgriGuardian isn't affiliated with these tools.",
    pwmBitwarden: "Open source, the safe default",
    pwm1Password: "Established, best for families",
    pwmKeeper: "Long track record, never breached",
    pwmProtonPass: "Newer, from an established company",
    recActionYellowMfa: "Check for device software updates and confirm that your account has multi-factor authentication (MFA) enabled.",
    deviceTypeLabel: "Device type",
    resolveOther: "Other",
    credWarning: "Never enter usernames, passwords, or credentials here.",
    notePlaceholder: "Add notes about this device — actions taken, observations, dealer contact, etc.",
    netNotePlaceholder: "Notes about actions taken, follow-up needed, etc.",
    requiredLabel: "* required",
    deviceDetails: "Device details",
    backToDevices: "Back to devices",
    resolvedMsg: "This issue was marked as resolved",
    recActionResolved: "No action needed at this time — this issue has been addressed. Keep monitoring and re-evaluate if anything changes.",
    monitorMsg2: "Continue to monitor and re-evaluate if anything changes.",
    verifiedMsg: "This device appears secure.",
    tapVerify2: "Tap below to verify it is still secure.",
    lastVerifiedOn: "Last verified",
    resolveTitle: "Has this issue been addressed?",
    resolveCheck: "I have addressed this issue",
    saveBtn: "Save",
    verifyTodayBtn: "Mark as verified today",
    resolvedBadgeLabel: "Marked resolved:",
    healthWarningText: "Never enter usernames, passwords, or login credentials here.",
    saveHealthBtnText: "Save verification",
    healthLastVerified: "Last verified:",
    sessionWarning: "Session expiring in",
    staySignedIn: "Stay signed in", userLabel: "Signed in as:",
    escTitle: "Can't fix this yourself?",
    escDesc: "Use this if the issue can't be resolved at your level (for example end-of-life equipment, needs purchasing approval, or needs vendor support). It will be sent to {target} to action — the Owner will be notified.",
    escReasonLabel: "Reason for escalating",
    escReasonPlaceholder: "Select a reason…",
    escReasons: ["End of life — device should be retired", "End of service — no more updates from the manufacturer", "Needs replacement purchase", "Needs vendor / dealer involvement", "Outside my permissions", "Other"],
    escNoteLabel: "Detail for {target} (optional)",
    escNotePlaceholder: "What did you see, and what needs to be decided?",
    escSendBtn: "Send to {target}",
    escPill: "Needs action",
    escBannerTitle: "Sent to you — needs your decision",
    escBannerFyiTitle: "Flagged — your Manager is handling this",
    escBannerFyiDesc: "This device was escalated to {name}. You can monitor progress here or step in if needed.",
    escBannerBy: "Flagged by",
    escBannerOn: "on",
    escBannerReason: "Reason",
    escBannerNote: "Note",
    escTakeOwnership: "Take ownership",
    escStepInBtn: "Step in as Owner",
    escResolveNow: "Resolve now",
    escClearedBadge: "Taken ownership",
    escDashLabel: "Flagged — needs action",
    escFilterNotice: "Showing only flagged items.",
    escClearFilter: "Show all devices",
    escSelectReason: "Please pick a reason before sending.",
    escAlreadyOpen: "This item has already been escalated.",
  },
  es: {
    appTag: "Defendiendo contra depredadores cibernéticos",
    navDash: "Tablero", navDevices: "Dispositivos", navAdd: "Agregar dispositivo",
    totalDevices: "Total dispositivos", actNow: "Actuar ahora", actionSoon: "Actuar pronto",
    highPriority: "Mayor prioridad", allDevices: "Todos los dispositivos",
    addDevice: "+ Agregar dispositivo", addTitle: "Agregar dispositivo",
    brand: "Marca", selectBrand: "Seleccionar marca...", deviceType: "Tipo de dispositivo",
    selectType: "Seleccionar tipo...", deviceLabel: "Nombre del dispositivo",
    labelPlaceholder: "ej. Sensor campo norte #3", optional: "(opcional)",
    pwChanged: "¿Se cambió la contraseña predeterminada?",
    addBtn: "Agregar dispositivo y verificar riesgo",
    lookingGood: "Todo bien", takeAction: "Actuar pronto", actNowBadge: "Actuar ahora",
    backBtn: "Volver a dispositivos",
    detailBrand: "Marca", detailType: "Tipo", detailPw: "Contraseña cambiada",
    detailSupport: "Soporte del fabricante", detailCve: "Vulnerabilidades conocidas",
    detailAutoUpdate: "Actualización automática", detailFirmware: "Última actualización",
    pwYesVal: "Sí", pwNoVal: "No / no estoy seguro", cveFound: "encontradas", cveNone: "Ninguna registrada",
    resolveNoteLabel: "Opcional: agregar nota sobre lo que se hizo...",
    resolveWarning: "Nunca ingrese nombres de usuario, contraseñas o credenciales aquí.",
    lookingGoodMsg: "Este dispositivo parece seguro.",
    tapVerify: "Toque abajo para verificar que sigue seguro.",
    monitorMsg: "Continúe monitoreando y reevalúe si algo cambia.",
    resolvedBadge: "Marcado resuelto:",
    healthStatus: "Estado de verificación",
    healthOpts: ["🟢 Se actualiza automáticamente","🟡 Lo actualizo yo mismo","🔴 Sin actualizaciones para este dispositivo"],
    healthTitle: "Actualizaciones de software del dispositivo",
    healthNotes: "Notas de verificación (opcional)",
    healthNotePlaceholder: "ej. Software actualizado por técnico en junio 2026",
    healthWarning: "Nunca ingrese credenciales de inicio de sesión aquí.",
    saveHealthBtn: "Guardar verificación",
    healthStamp: "Última verificación:",
    alertMsg1: "dispositivo requiere atención inmediata.",
    alertMsgN: "dispositivos requieren atención inmediata.",
    loginTitle: "Bienvenido a AgriGuardian", loginSub: "Defendiendo contra depredadores cibernéticos",
    loginPhone: "Número de teléfono", loginCode: "Código de verificación",
    loginSend: "Enviar código", loginVerify: "Verificar e ingresar", loginRole: "Su función",
    loginRoles: ["Propietario","Gerente","Técnico","Trabajador","Observador"],
    loginFarm: "Nombre de la finca",
    loginName: "Su nombre",
    loginEmailOpt: "(opcional — para informes)",
    loginRegTitle: "Crear su cuenta",
    loginRegSend: "Enviar código de verificación",
    loginWelcomeTitle: "Bienvenido",
    loginWelcomeSub: "¿Es usted un usuario nuevo o regresando?",
    loginCreateBtn: "Crear una cuenta",
    loginSigninBtn: "Iniciar sesión en cuenta existente",
    loginSigninTitle: "Iniciar sesión",
    loginSigninSub: "Ingrese el número de teléfono con el que se registró.",
    loginVerifyTitle: "Verificar su número",
    loginBack: "Atrás",
    lockoutMsg: "Demasiados intentos fallidos. Espere {n} segundos antes de intentarlo de nuevo.",
    lockoutBanner: "Cuenta temporalmente bloqueada. Espere",
    lockoutSeconds: "segundos.",
    lockoutMinutes: "minutos.",
    forgotPassword: "¿Olvidó su contraseña?",
    resetTitle: "Restablecer contraseña",
    resetSub: "Ingrese su número de teléfono y le enviaremos un código de restablecimiento.",
    resetPhone: "Su número de teléfono",
    resetSendBtn: "Enviar código de restablecimiento",
    resetCodeLabel: "Código de verificación",
    resetNewPw: "Nueva contraseña",
    resetConfirmBtn: "Establecer nueva contraseña",
    resetSuccess: "¡Contraseña actualizada correctamente! Inicie sesión con su nueva contraseña.",
    attemptsRemaining: "intento restante",
    attemptsRemainingPlural: "intentos restantes",
    loginLockoutNote: "En producción, el bloqueo se aplica del lado del servidor y está vinculado a la cuenta — actualizar la página no lo restablecerá.",
    editMemberTitle: "Editar miembro",
    saveChangesBtn: "Guardar cambios",
    auditLogTitle: "Registro de auditoría",
    noAuditActivity: "No se ha registrado actividad aún.",
    auditShowingLast: "Mostrando los últimos",
    auditAction: "acción",
    auditActions: "acciones",
    productionSecTitle: "Seguridad en producción",
    encHead: "Cifrado de datos:",
    backupHead: "Estrategia de copias de seguridad:",
    archHead: "Arquitectura:",
    perfHead: "Rendimiento:",
    encryptionNote: "Todos los datos cifrados en tránsito (TLS) y en reposo (AES-256) en producción.",
    backupNote: "Copias de seguridad diarias automatizadas con retención de 30 días planificadas para producción.",
    architectureNote: "Funciones principales en la aplicación base. Análisis avanzados ofrecidos como complementos opcionales.",
    performanceNote: "La aplicación se evalúa en cuanto a tiempo de carga y eficiencia de base de datos en cada hito de lanzamiento.",
    loginFarmTz: "Zona horaria de la finca",
    aboutLabel: "Acerca de",
    accessibilityLabel: "Accesibilidad",
    addNetworkConn: "Agregar una conexión de red",
    addNetworkBtn: "Agregar conexión de red",
    addDeviceBtn: "+ Agregar dispositivo",
    addADevice: "Agregar un dispositivo",
    addANetwork: "Agregar una conexión de red",
    brandLabel: "Marca",
    selectBrand: "Seleccionar marca...",
    otherNotListed: "Otro / No está en la lista",
    mfrModelNum: "Número de modelo del fabricante",
    usedForLookups: "(usado para búsquedas de seguridad)",
    usedForVulnLookups: "(usado para búsquedas de vulnerabilidades)",
    deviceNameLabel: "Nombre o etiqueta del dispositivo",
    selectLocation: "Seleccionar ubicación...",
    addCustomLocation: "+ Agregar ubicación personalizada...",
    selectConnType: "Seleccionar tipo de conexión...",
    selectType: "Seleccionar tipo...",
    hasPwChanged: "¿Se cambió la contraseña predeterminada?",
    isEncrypted: "¿Esta red está cifrada?",
    yesEncrypted: "Sí (WPA2/WPA3 o equivalente)",
    routerBrand: "Marca del router / módem",
    selectBrandNet: "Seleccionar marca...",
    modelNumLabel: "Número de modelo",
    uniqueTypeNote: "Los nombres de tipo de dispositivo deben ser únicos (sin distinción de mayúsculas).",
    uniqueRoleNote: "Los nombres de rol deben ser únicos (sin distinción de mayúsculas).",
    uniqueBrandNote: "Los nombres de marca deben ser únicos (p. ej. John Deere y johndeer se considerarían iguales).",
    enterBrandPlaceholder: "Ingresar nombre de marca",
    modelPlaceholder: "p.ej. JD4066R, ValleyX",
    serialPlaceholder: "p.ej. NS-2024-88471",
    enterTypePlaceholder: "Ingresar tipo de dispositivo",
    deviceLabelPlaceholder: "p.ej. Sensor campo norte #3",
    customLocationPlaceholder: "p.ej. Campo Abeja, Parcela 40, Granero Trasero",
    dealerPlaceholder: "p.ej. Distribuidor: Ag Supply Co — Juan Smith 555-2341",
    netNamePlaceholder: "p.ej. Wi-Fi de la finca, Router del granero",
    netModelPlaceholder: "p.ej. Netgear Nighthawk R7000, Cisco RV340",
    memberNamePlaceholder: "p.ej. Sara Tully",
    customRolePlaceholder: "Ingresar nombre de rol personalizado",
    cameraType: "Cámara / seguridad",
    sessionTitle5min: "5 minutos (demo)",
    sessionTitle15min: "15 minutos",
    sessionTitle30min: "30 minutos",
    sessionTitle1hr: "1 hora",
    sessionShortNote: "Se recomienda un tiempo de espera más corto para dispositivos compartidos o de campo.",
    onOffOff: "Apagado",
    onOffOn: "Encendido",
    nvdLabel: "NVD — Base de Datos Nacional de Vulnerabilidades",
    nvdDesc: "NVD proporciona registros CVE detallados con búsqueda por número de modelo. En producción, AgriGuardian se conectaría a NVD a través de un servidor backend seguro — la clave API nunca estaría expuesta al navegador.",
    nvdArchNote: "La clave API de NVD vive en el servidor de AgriGuardian. La aplicación envía una solicitud al servidor, el servidor llama a NVD y devuelve los resultados — la clave nunca toca el navegador. Esta es una práctica estándar para proteger las credenciales de API en aplicaciones web.",
    prodArchLabel: "Arquitectura de producción:",
    allRightsLabel: "Todos los derechos reservados.",
    protoLabel: "Prototipo — Versión Alpha",
    createdByLabel: "Creado por",
    addTeamMemberTitle: "Agregar un miembro del equipo",
    farmTimezoneLabel: "Zona horaria de la finca",
    assignRoleLabel: "Asignar rol",
    addNewRoleOption: "+ Agregar nuevo rol...",
    sortByLabel: "Ordenar por:",
    farmAccountHeader: "Cuenta de la finca",
    teamMembersHeader: "Miembros del equipo",
    timezoneHeader: "Zona horaria de la finca",
    sessionHeader: "Configuración de sesión",
    workerDetails: "Ingrese los detalles del trabajador. Recibirán una invitación por SMS para descargar AgriGuardian y unirse a la cuenta de su finca.",
    memberFullName: "Nombre completo",
    selectTeamMember: "Seleccionar un miembro del equipo...",
    whatWasDone: "¿Qué se hizo?",
    notesHeader: "Notas",
    riskLevelSort: "Nivel de riesgo",
    netRiskWhyNoPw: "La contraseña predeterminada no ha sido cambiada — un vector de ataque común.",
    netRiskWhyNoEnc: "Esta conexión no está cifrada — los datos pueden ser interceptados.",
    netRiskWhyGood: "Esta conexión parece segura. Continúe monitoreando.",
    noteJohnDeere: "Autenticación basada en la nube a través de Operations Center. MFA disponible y recomendado.",
    noteValley: "Los controladores de panel más antiguos pueden usar credenciales predeterminadas. El portal en la nube (Valley 365) admite MFA.",
    noteHogSlat: "Interfaz web local con autenticación débil. Sin MFA disponible. Las contraseñas predeterminadas están documentadas públicamente.",
    noteDeLaval: "Los controladores de granero a menudo usan credenciales predeterminadas. Solo inicio de sesión local en unidades antiguas.",
    noteTrimble: "Cuenta en la nube con MFA disponible. Mantenga los dispositivos de campo actualizados a través del portal de Trimble.",
    noteDJI: "MFA disponible a través de la cuenta DJI. La autenticación basada en la aplicación es segura cuando la cuenta está configurada correctamente.",
    noteArable: "Dispositivo centrado en la nube. Sin inicio de sesión local. MFA compatible en el portal de Arable.",
    noteOther: "Dispositivo no está en nuestra base de datos. Aplique orientación de seguridad general y comuníquese con el fabricante.",
    riskWhyNoPw: "La contraseña predeterminada no ha sido cambiada — una vulnerabilidad conocida que los atacantes escanean activamente.",
    riskWhyCve: "Esta marca de dispositivo tiene {n} vulnerabilidades de seguridad conocidas registradas en bases de datos públicas.",
    riskWhyCve1: "Esta marca de dispositivo tiene {n} vulnerabilidad de seguridad conocida registrada en bases de datos públicas. Confirme que haya sido corregida.",
    riskWhyLimited: "El soporte del fabricante es limitado, lo que significa que es posible que no se emitan parches de seguridad para nuevas vulnerabilidades.",
    riskWhyUnknown: "Este dispositivo no está en nuestra base de datos. Recomendamos aplicar orientación de seguridad general.",
    describeWhatDone: "Describa lo que se hizo...",
    verifyDeviceSecure: "Verifique que este dispositivo siga siendo seguro",
    verifyAgain: "Verificar de nuevo",
    verifyStaleNote: "Ha pasado un tiempo desde la última revisión. Última verificación:",
    optional: "(opcional)",
    brandSort: "Marca",
    nameSort: "Nombre",
    locationSort: "Ubicación",
    addNetworkBtnShort: "+ Agregar red",
    connWifi: "Wi-Fi",
    connEthernet: "Ethernet (por cable)",
    connCellular: "Celular (LTE/5G)",
    connSatellite: "Satélite",
    connBluetooth: "Bluetooth",
    connLoRa: "LoRa",
    connUnknown: "Desconocido",
    a11yColorBlindDesc: "Agrega formas junto a los colores para los niveles de riesgo",
    a11yDisableMotion: "Desactiva las transiciones y animaciones",
    a11yExtraLarge: "Texto extra grande",
    a11yExtraLargeDesc: "Tamaño máximo de texto para visión reducida",
    a11yHighContrast: "Alto contraste",
    a11yHighContrastDesc: "Mayor contraste entre texto y fondos",
    a11yLargeText: "Texto grande",
    a11yLargeTextDesc: "Aumenta el tamaño del texto en toda la aplicación",
    a11yReducedMotion: "Movimiento reducido",
    cisaLabel: "Vulnerabilidades conocidas explotadas de CISA",
    connectedLabel: "Conectado",
    connTypeLabel: "Tipo de conexión",
    fullName: "Nombre completo",
    issuesLabel: "Problemas",
    nameOrLabel: "Nombre o etiqueta",
    networkConns: "Conexiones de red",
    networksLabel: "Redes",
    passwordLabel: "Contraseña",
    pendingBackend: "Integración de backend pendiente",
    riskLevelLabel: "Nivel de riesgo",
    sendMfa: "Enviar código MFA",
    timeZoneDesc: "Zona horaria utilizada para todas las marcas de tiempo",
    verifyIdentity: "Verificar su identidad",
    vulnDatabases: "Bases de datos de vulnerabilidades",
    locationNorthField: "Campo norte", locationSouthField: "Campo sur",
    locationEastField: "Campo este", locationWestField: "Campo oeste",
    locationMainHouse: "Casa principal", locationGrainBins: "Silos de grano",
    locationDairyBarn: "Establo lechero", locationMachineShed: "Cobertizo",
    typeIrrigation: "Controlador de riego",
    typeLivestock: "Monitor de ganado",
    typeSoil: "Sensor de suelo", typeFeed: "Sistema de alimentación",
    typeBarnVent: "Controlador de ventilación del granero",
    roleManager: "Gerente", roleTechnician: "Técnico",
    roleFarmHand: "Trabajador agrícola", roleViewer: "Observador",
    loginPassword: "Crear una contraseña",
    loginPassHint: "Las reglas de complejidad de contraseña se aplicarán en producción.",
    loginPassPlaceholder: "Mín. 8 caracteres",
    loginDemoTitle: "Cómo explorar esta demo",
    loginDemoStep1: "Toque",
    loginDemoStep1b: "— los campos están prellenados.",
    loginDemoStep2: "Toque",
    loginDemoStep3: "Ingrese el código de demo:",
    loginDemoStep4: "Toque",
    loginDemoStep4b: "para explorar la aplicación.",
    loginDemoCode: "Código de demo: 123456",
    loginHaveInviteBtn: "Tengo una invitación",
    loginDemoSubTitle: "Tres formas de entrar — elija una:",
    loginDemoCard1Title: "1. Crear una cuenta → Modo propietario",
    loginDemoCard1Desc: "Complete la configuración del propietario. Los campos están prellenados. Código de verificación: 123456",
    loginDemoCard2Title: "2. Iniciar sesión → cuentas demo ya creadas",
    loginDemoCard2Desc: "Toque Iniciar sesión y elija un miembro del equipo prediseñado para ver la aplicación desde su perspectiva. Código de verificación: 123456",
    loginDemoCard3Title: "3. Tengo una invitación → unirse a una finca existente",
    loginDemoCard3Desc: "Toque Tengo una invitación e ingrese el código 987654 para ver cómo un nuevo miembro del equipo acepta una invitación de la finca. El registro es solo de lectura.",
    loginLastUpdated: "Última actualización:",
    loginOptionalReport: "(opcional — para informes)",
    loginUsernameHint: "(este es su nombre de usuario)",
    loginVerificationSent: "Se envió un código de verificación a su teléfono.",
    loginPhoneUsername: "Su número de teléfono es su nombre de usuario.",
    loginNewOrReturning: "¿Usuario nuevo o regresando?",
    loginVerifyBtn: "Verificar e ingresar",
    loginSendMfa: "Enviar código MFA",
    loginPasswordLabel: "Contraseña",
    loginPhonePlaceholder: "(555) 000-0000",
    loginCodePlaceholder: "123456",
    loginYourPhone: "Su número de teléfono",
    loginEmail: "Correo electrónico",
    loginEmailPlaceholder: "usted@ejemplo.com",
    loginEmailNote: "opcional — para informes",
    settingsTitle: "Configuración de la finca",
    farmInfo: "Cuenta de la finca",
    teamTitle: "Miembros del equipo",
    addMember: "Agregar miembro del equipo",
    memberPhone: "Número de teléfono",
    memberRole: "Asignar función",
    inviteBtn: "Enviar invitación",
    inviteNote: "El trabajador recibirá un SMS con instrucciones para descargar AgriGuardian y unirse a su cuenta.",
    sessionTitle: "Configuración de sesión",
    timeoutLabel: "Cerrar sesión automáticamente por inactividad",
    timeoutNote: "Se recomienda un tiempo más corto para dispositivos compartidos o de campo.",
    securityTitle: "Seguridad",
    pwRulesLabel: "Requisitos de contraseña",
    pwRulesText: "Las reglas de complejidad de contraseña se aplicarán en producción.",
    navSettings: "Configuración",
    pwYes: "Sí, lo cambié", pwNo: "No / no estoy seguro",
    detailPwYes: "Sí", detailPwNo: "No / no estoy seguro",
    resolveActions: ["Contraseña cambiada","Dispositivo desconectado de la red","Dispositivo reemplazado","Software del dispositivo actualizado","MFA habilitado","Monitoreando situación"],
    netActions: ["Contraseña cambiada","Cifrado habilitado","Red segmentada","Router reemplazado","Monitoreo habilitado"],
    otherLabel: "Otro",
    locationLabel: "Ubicación", connectionLabel: "Conexión",
    modelLabel: "Número de modelo", serialLabel: "Número de serie",
    macLabel: "Dirección MAC",
    macFieldLabel: "Dirección MAC",
    macHint: "Ayuda a distinguir dos dispositivos del mismo modelo.",
    dealerLabel: "Distribuidor e información de contacto",
    hardwareBrand: "Marca del hardware", hardwareModel: "Número de modelo",
    netNotesLabel: "Notas", netAdditionalNotes: "Notas adicionales",
    hwVulnCheck: "Verificar vulnerabilidades conocidas",
    resolvedOn: "Marcado resuelto:", verifiedOn: "Última verificación:",
    noTeamMembers: "No se encontraron miembros del equipo.",
    invitedStatus: "Invitado", activeStatus: "Activo", archivedStatus: "Archivado",
    permAdd: "Agregar dispositivos", permArchive: "Archivar / eliminar dispositivos",
    permResolve: "Resolver problemas y actualizar estado del dispositivo",
    permAssign: "Asignar problemas a miembros del equipo",
    permExport: "Exportar y descargar informes",
    tlTitle: "Historial del dispositivo",
    tlAdded: "Dispositivo agregado a AgriGuardian",
    tlFlaggedHigh: "Marcado como riesgo alto",
    tlFlaggedAttention: "Marcado — requiere atención",
    tlAssigned: "Asignado a",
    tlHealthSet: "Estado de actualización registrado:",
    tlResolved: "Problema atendido",
    tlVerified: "Verificado como seguro",
    assignTitle: "Asignar este problema",
    assignDesc: "Designe a alguien como responsable de atender este problema.",
    assignSelectPlaceholder: "Seleccione un miembro del equipo…",
    assignBtn: "Asignar",
    reassignBtn: "Reasignar",
    unassignBtn: "Quitar asignación",
    assignedToLabel: "Asignado a",
    unassignedLabel: "Sin asignar todavía",
    assignNoteLabel: "Instrucciones / qué hacer",
    assignViewOnlyGroup: "Solo lectura (solo instrucci\u00F3n)",
    assignViewOnlyHint: "Las personas de solo lectura no pueden resolver problemas; su nota es una instrucci\u00F3n para ellas.",
    assignNotePresets: ["Puede seguir us\u00E1ndolo", "Consulte con la gerencia antes de continuar", "No usar hasta revisar"],
    assignedInstructionLabel: "Instrucci\u00F3n para usted",
    assignNotePlaceholder: "¿Qué debe verificar o corregir esta persona?",
    noAssignableMembers: "No hay miembros del equipo disponibles para asignar. Agregue miembros activos en Configuración primero.",
    handoffNoteRequired: "Se requiere una nota en cada traspaso. Por favor describa qué debe hacerse.",
    handoffNoteLabel: "Nota / qué va a hacer",
    handoffLogTitle: "Historial de traspasos",
    handoffTypeAssign: "Asignado",
    handoffTypeEscalate: "Escalado",
    handoffTypeSendBack: "Devuelto",
    handoffTypePartialFix: "Corrección parcial",
    handoffTypeResolved: "Totalmente resuelto",
    handoffTypeTakeOwnership: "Asumió responsabilidad",
    takeOwnershipNotePlaceholder: "¿Qué va a hacer para atender esto? (ej. contactar al proveedor, gestionar reemplazo)",
    returnedBannerTitle: "Devuelto con instrucciones",
    returnedBannerFrom: "De",
    returnedBannerHint: "Revise las instrucciones anteriores, luego resuelva o vuelva a escalar si es necesario.",
    sendBackBtn: "Devolver al técnico",
    sendBackNoteLabel: "Instrucciones para el técnico",
    sendBackNotePlaceholder: "¿Qué debe intentar, verificar o hacer antes de volver a escalar?",
    sendBackConfirmBtn: "Devolver con instrucciones",
    dashFarmStatus: "Estado de la finca",
    dashDeviceProblems: "Problemas con dispositivos",
    dashNetworkProblems: "Problemas de red",
    dashAssignedWork: "Trabajo asignado",
    dashUnassigned: "Sin asignar — necesita responsable",
    dashMyWork: "Mi trabajo asignado",
    returnedDashLabel: "Devuelto al técnico",
    issuesSingular: "problema",
    issuesPlural: "problemas",
    noIssues: "Todo bien",
    allGoodMsg: "Todo está bien. No se encontraron problemas.",
    techNoWorkMsg: "No tiene trabajo asignado ni problemas abiertos sin asignar en este momento.",
    partiallyResolvedBadge: "Parcialmente resuelto",
    partialEscBannerTitle: "Parcialmente resuelto — se requiere decisión",
    partialEscWhatFixed: "Lo que {name} ya corrigió",
    partialEscWhatRemains: "Lo que aún requiere una decisión",
    partialEscHandledBy: "Actualmente asignado a {name} — o intervenga a continuación para asumirlo usted mismo.",
    logViewedTab: "Vio la pestaña {tab}",
    logViewedDevice: "Vio el dispositivo — {device}",
    logViewedNetwork: "Vio la red — {network}",
    partialResolveTitle: "Corrige lo que puedas + escala el resto",
    partialResolveDesc: "Úsalo cuando puedas atender parte del problema tú mismo (ej. cambiar la contraseña) pero algo más requiere una decisión del Gerente o Propietario (ej. equipo al final de su vida útil). Ambas acciones se registran en un solo paso.",
    partialFixNoteLabel: "¿Qué corregiste / qué hiciste?",
    partialFixNotePlaceholder: "ej. Cambié la contraseña predeterminada. El dispositivo aún necesita reemplazo — el fabricante ya no emite actualizaciones de firmware.",
    partialFixNoteRequired: "Por favor describa qué corrigió antes de enviar.",
    partialFixByLabel: "Corregido por",
    partialResolveBtn: "Corregir mi parte y escalar a {target}",
    partialResolveStepPw: "Paso 1 — Cambie la contraseña predeterminada de este dispositivo primero, luego registre lo que hizo a continuación.",
    partialDashLabel: "Parcialmente resuelto — requiere decisión",
    required: "obligatorio",
    viewOnlyIssueNote: "Tiene acceso de solo lectura. Comuníquese con el propietario de la finca para atender o asignar este problema.",
    permView: "Solo lectura (anula todas las anteriores)",
    restoreBtn: "Restaurar", archiveBtn: "Archivar",
    permissionsLabel: "Permisos",
    navNetwork: "Red",
    archive: "Archivar", archiving: "Archivar", delete: "Eliminar", restore: "Restaurar",
    archived: "Archivado", active: "Activo", allLabel: "Todo",
    permissions: "Permisos",
    defaultPwChanged: "Contraseña predeterminada cambiada",
    manufacturerSupport: "Soporte del fabricante",
    knownVulnerabilities: "Vulnerabilidades conocidas",
    lastSoftwareUpdate: "Última actualización de software",
    notes: "Notas",
    additionalNotes: "Notas adicionales",
    sending: "Enviando...",
    keySaved: "Clave guardada para esta sesión.",
    backToNetwork: "Volver a conexiones de red",
    signedOutInactivity: "Se cerró la sesión por inactividad.",
    verificationSentTo: "Se envió un código de verificación a ",
    invitationSentTo: "Invitación enviada a ",
    timeZoneUpdatedTo: "Zona horaria actualizada a ",
    permanentlyDelete: "Eliminar permanentemente ",
    enterBrandName: "Ingrese un nombre de marca.",
    enterDeviceType: "Ingrese un tipo de dispositivo.",
    enterPhone: "Ingrese un número de teléfono.",
    enterMemberName: "Ingrese el nombre del miembro del equipo.",
    enterVerification: "Ingrese el código de verificación.",
    fillAllFields: "Complete todos los campos.",
    alreadyInvited: "Este número ya fue invitado.",
    enterRoleName: "Ingrese un nombre para el nuevo rol.",
    incorrectCode: "Código incorrecto. Para esta demo use: 123456",
    archiveUserPrompt: "¿Por qué se archiva este miembro?",
    archiveNote: "Se requiere una nota. Su historial se conservará.",
    archiveReason: "Razón de archivo:",
    archiveDeviceConfirm: "¿Archivar este dispositivo? Se ocultará de su lista activa pero se conservará el historial.",
    archiveNetConfirm: "¿Archivar esta red? Se ocultará pero se conservará el historial.",
    restoreDeviceConfirm: "¿Restaurar este dispositivo?",
    deleteDeviceWarn: "ADVERTENCIA: Este dispositivo tiene registros existentes.\n\nEliminarlo borrará permanentemente todo su historial.\n\nRecomendamos Archivar en su lugar.\n\nToque OK para eliminar de todas formas.\nToque Cancelar para volver.",
    deleteDeviceConfirm: "¿Eliminar permanentemente este dispositivo? Esto no se puede deshacer.",
    recActionRed: "Desconecte este dispositivo de su red hasta que se cambie la contraseña predeterminada y el dispositivo esté asegurado. Comuníquese con su distribuidor para obtener asistencia.",
    recActionYellowNoPw: "Cambie la contraseña predeterminada de este dispositivo hoy. Consulte el sitio web del fabricante o comuníquese con su distribuidor para obtener instrucciones paso a paso.",
    recActionYellow: "Este dispositivo tiene alertas de seguridad activas. Revise las vulnerabilidades conocidas y asegúrese de que el software esté actualizado.",
    recActionGreen: "Este dispositivo parece seguro. Continúe monitoreando y mantenga el software actualizado.",
    pwmTitle: "Use un gestor de contraseñas",
    fdlTitle: "Encuentre el acceso predeterminado",
    fdlIntro: "Este dispositivo puede seguir usando el acceso con el que vino. Encuéntrelo, inicie sesión una vez y cámbielo por una contraseña fuerte y única.",
    fdlLabelTitle: "Revise el dispositivo mismo",
    fdlLabelBody: "Muchos tienen una etiqueta en la parte inferior o trasera con el acceso predeterminado.",
    fdlManualTitle: "Revise el manual o la guía de inicio rápido",
    fdlManualBody: "Busque el acceso predeterminado en el sitio de soporte del fabricante para",
    fdlDealerTitle: "Pregunte a su distribuidor",
    fdlDealerOnFile: "En archivo:",
    fdlWarning: "Cámbielo de inmediato. Un acceso predeterminado es de conocimiento público y la forma principal en que los dispositivos son comprometidos.",
    pwmIntro: "Este dispositivo todavía usa su contraseña predeterminada. Un gestor de contraseñas crea y recuerda una contraseña fuerte y única por usted.",
    pwmNeverStores: "AgriGuardian nunca ve ni almacena sus contraseñas. Guárdelas en el gestor, no aquí.",
    pwmTrustedOptions: "Opciones de confianza",
    pwmFreeTag: "Gratis",
    pwmVisit: "Visitar",
    pwmDisclaimer: "Solo sugerencias. AgriGuardian no está afiliado con estas herramientas.",
    pwmBitwarden: "Código abierto, la opción segura por defecto",
    pwm1Password: "Establecido, ideal para familias",
    pwmKeeper: "Larga trayectoria, nunca vulnerado",
    pwmProtonPass: "Más reciente, de una empresa establecida",
    recActionYellowMfa: "Verifique si hay actualizaciones de software del dispositivo y confirme que su cuenta tiene autenticación de múltiples factores (MFA) habilitada.",
    deviceTypeLabel: "Tipo de dispositivo",
    resolveOther: "Otro",
    credWarning: "Nunca ingrese nombres de usuario, contraseñas o credenciales aquí.",
    notePlaceholder: "Agregue notas sobre este dispositivo — acciones tomadas, observaciones, contacto del distribuidor, etc.",
    netNotePlaceholder: "Notas sobre las acciones tomadas, seguimiento necesario, etc.",
    requiredLabel: "* requerido",
    typeNetGateway: "Puerta de enlace de red",
    typeGPS: "Sistema GPS / guía",
    typeAutomation: "Controlador de automatización",
    typeRoboticMilker: "Ordeñador robótico",
    typeWeather: "Estación meteorológica",
    typeDrone: "Dron",
    locationBarn: "Granero",
    locationPasture: "Pastizal",
    fixBtn: "Corregir →",
    reviewBtn: "Revisar →",
    hygieneTitle: "Puntaje de Higiene de la Finca",
    hygieneOutOf: "de 100",
    hygienePassword: "Higiene de contraseñas",
    hygieneUpdate: "Higiene de actualizaciones",
    hygieneNetwork: "Higiene de red",
    hygieneApps: "Higiene de aplicaciones",
    hygieneBackup: "Higiene de respaldos",
    navBackups: "Respaldos",
    backupScreenTitle: "Estado de respaldo 3-2-1",
    backup321Title: "Sus 3 copias",
    backup321Copy1Label: "Copia 1 — Principal (en la finca)",
    backup321Copy2Label: "Copia 2 — Segundo formato",
    backup321Copy3Label: "Copia 3 — Fuera del sitio",
    backup321Copy1Short: "Copia principal",
    backup321Copy2Short: "Copia en segundo formato",
    backup321Copy3Short: "Copia fuera del sitio",
    backup321Copy1Placeholder: "ej. PC de la finca + Time Machine en disco externo",
    backup321Copy2Placeholder: "ej. NAS Synology en la oficina del granero, o Google Drive",
    backup321Copy3Placeholder: "ej. Nube Backblaze B2 (automático nocturno), o disco guardado en casa",
    backup321Copy1Note: "Donde viven sus datos día a día",
    backup321Copy2Note: "Un dispositivo o servicio diferente al principal",
    backup321Copy3Note: "Físicamente o geográficamente separado de la finca",
    backupHaveThisCopy: "Tenemos esta copia",
    backupLastVerified: "Última verificación (respaldos probados)",
    backupUpdateTitle: "Actualizar estado de respaldo",
    backupNotesPlaceholder: "ej. Respaldo automático nocturno con Backblaze — restauración de prueba realizada en marzo de 2026",
    backupRiskWhyMissing: "Falta: {copies}. Se necesitan las tres copias para una protección 3-2-1 completa.",
    backupRiskWhyNeverVerified: "Las tres copias están configuradas pero nunca se han verificado — un respaldo no probado puede no restaurarse correctamente.",
    backupRiskWhyStale: "Los respaldos no han sido verificados en más de 90 días — haga una restauración de prueba para confirmar que todo sigue funcionando.",
    backupRiskWhyGood: "La regla de respaldo 3-2-1 está en vigor y fue verificada recientemente.",
    backupRecActionRed: "Configure las copias de respaldo faltantes. Comience con un disco externo (Copia 2) y un servicio en la nube como Backblaze (Copia 3).",
    backupRecActionNeverVerified: "Todas las copias están configuradas — ahora pruebe una restauración. Intente recuperar un archivo de cada respaldo para confirmar que realmente funciona.",
    backupRecActionStale: "Verifique sus respaldos restaurando un archivo de prueba. Confirme que su copia fuera del sitio esté actualizada.",
    backupRecActionGood: "No se requiere ninguna acción. Verifique de nuevo en 90 días y tras cualquier cambio importante en los datos.",
    navApps: "Apps",
    backToApps: "Volver a las apps",
    appsTitle: "Aplicaciones que usa la finca",
    addApp: "+ Agregar app",
    addAnApp: "Agregar una aplicación",
    noAppsYet: "Aún no se han agregado aplicaciones.",
    appNameLabel: "Nombre de la app o servicio",
    appNamePlaceholder: "ej. QuickBooks Online, Climate FieldView",
    appVendorLabel: "Proveedor",
    appVendorPlaceholder: "ej. Intuit, Bayer",
    appPurposeLabel: "¿Para qué se usa?",
    appPurposePlaceholder: "ej. Contabilidad y nómina de la finca",
    appReviewedQuestion: "¿Esta app ha sido revisada por seguridad?",
    appAccountOwnerLabel: "Propietario de la cuenta",
    appAccountOwnerPlaceholder: "ej. Angus MacDonald",
    appRenewalLabel: "Renovación / costo",
    appRenewalPlaceholder: "ej. $35/mes, se renueva en enero de 2027",
    appMfaLabel: "Autenticación de múltiples factores (MFA)",
    appMfaQuestion: "¿Está habilitada la autenticación de múltiples factores (MFA)?",
    appPwManagerLabel: "Gestor de contraseñas",
    appPwManagerQuestion: "¿La contraseña de esta app está guardada en un gestor de contraseñas?",
    appPwManagerNamePlaceholder: "ej. Bitwarden, 1Password",
    appPwManagerWarning: "⚠️ Ingrese únicamente el nombre del gestor de contraseñas utilizado — nunca la contraseña en sí ni su contraseña maestra.",
    appPickerLabel: "Elija una app común, o seleccione Otra",
    appPickerSelect: "Seleccione una app...",
    appPickerOther: "Otra / no listada",
    addAppBtn: "Agregar app",
    appDetailsTitle: "Detalles de la app",
    appReviewedLabel: "Revisión de seguridad",
    appLastReviewedLabel: "Última revisión",
    appReviewBoxTitle: "Actualizar estado de revisión",
    appFlagInsecureLabel: "Marcar esta app como insegura / requiere atención",
    appNotePlaceholder: "ej. Se revisaron los permisos de acceso, se eliminó una integración sin uso",
    appRiskWhyFlagged: "Esta app ha sido marcada como insegura o que requiere atención.",
    appRiskWhyNeverReviewed: "Esta app aún no ha tenido una revisión de seguridad.",
    appRiskWhyNoMfa: "La autenticación de múltiples factores no está habilitada en esta app.",
    appRiskWhyStale: "Esta app no ha sido revisada en más de 6 meses.",
    appRiskWhyGood: "Esta app ha sido revisada recientemente y se ve bien.",
    appRecActionFlagged: "Revise la nota de la marca, atienda la inquietud y actualice el estado de revisión una vez resuelta.",
    appRecActionReview: "Revise el acceso a la cuenta, los permisos y la contraseña de esta app antes de marcarla como revisada.",
    appRecActionNoMfa: "Habilite la autenticación de múltiples factores (MFA) en esta cuenta lo antes posible.",
    appRecActionStale: "Han pasado más de 6 meses — haga una revisión rápida para confirmar que el acceso y los permisos siguen siendo correctos.",
    appRecActionGood: "No se requiere ninguna acción. Vuelva a revisar periódicamente, especialmente tras cambios de personal.",
    archiveAppConfirm: "¿Archivar {name}? Se ocultará de su lista activa pero se conservará su historial.",
    deleteAppConfirm: "¿Eliminar permanentemente {name}? Esto no se puede deshacer.",
    deleteAppWarn: "ADVERTENCIA: Esta app tiene historial de revisión existente.\n\nEliminarla borrará permanentemente ese historial.\n\nRecomendamos encarecidamente archivar en su lugar.\n\nToque Aceptar para eliminar permanentemente de todos modos.\nToque Cancelar para regresar.",
    pdfReportTitle: "Informe de Higiene Cibernética de la Finca",
    pdfYourFarm: "Su Finca",
    pdfGenerated: "Generado",
    pdfActionList: "Lista de Acciones Prioritarias",
    pdfNoActions: "No hay acciones de seguridad pendientes. Todo se ve bien.",
    pdfDeviceInventory: "Inventario de Dispositivos",
    pdfNetworks: "Conexiones de Red",
    pdfDevice: "Dispositivo",
    pdfNetwork: "Red",
    pdfType: "Tipo",
    pdfPwChanged: "Contraseña cambiada",
    pdfStatus: "Estado",
    pdfHigh: "Riesgo alto",
    pdfMedium: "Requiere atención",
    pdfLow: "Seguro",
    pdfResolved: "Resuelto",
    pdfYes: "Sí",
    pdfNo: "No",
    pdfDisclaimer: "Generado por AgriGuardian. Este informe refleja información de dispositivos autoinformada y datos de vulnerabilidades conocidas al momento de la generación. Se proporciona para el seguimiento de higiene y no es una garantía de seguridad.",
    pdfPopupBlocked: "Permita las ventanas emergentes para este sitio para descargar el informe.",
    lblDownloadReport: "Descargar PDF",
    lblDownloadActivity: "Descargar PDF",
    lblEmailReport: "Enviar por correo",
    lblEmailActivity: "Enviar por correo",
    lblReportHygieneTitle: "Informe de Higiene",
    lblReportActivityTitle: "Registro de Actividad",
    emailRequired: "Por favor ingrese su dirección de correo electrónico para usar esta función.",
    emailInvalid: "Por favor ingrese una dirección de correo electrónico válida.",
    viewOnlyBadge: "solo lectura",
    inviteBtn: "Tengo una invitación",
    loginDemoInviteHint: "O toque <strong>Tengo una invitación</strong> y use el código <strong style=\"background:#fff;padding:2px 8px;border-radius:6px;border:1px solid #C8E6C9;letter-spacing:1px\">987654</strong> para explorar como miembro del equipo.",
    inviteTitle: "Unirse a una finca",
    inviteSub: "Ingrese su código de invitación para comenzar.",
    inviteCodeLabel: "Código de invitación",
    inviteCodePlaceholder: "ej. 987654",
    inviteAccepted: "Código aceptado — complete su perfil a continuación",
    inviteYourName: "Su nombre",
    inviteYourPhone: "Teléfono",
    inviteRoleLabel: "Su rol",
    inviteReadonlyNote: "El nombre y el teléfono los configuró el dueño de la finca y no se pueden cambiar. Los registros de invitación demo son de solo lectura.",
    inviteDemoHintTitle: "ⓘ Código de invitación demo",
    inviteDemoHint: "Use el código 987654 para registrarse. Luego use \"Iniciar sesión\" para explorar como Carlos o Jamie.",
    inviteJoinBtn: "Unirse a Old McDonald's Farm",
    inviteContinueBtn: "Continuar",
    inviteBackBtn: "Atrás",
    demoMembersTitle: "ⓘ Explorar como miembro del equipo",
    demoMembersSub: "Toque un perfil para iniciar sesión como miembro del equipo prediseñado y ver su perspectiva.",
    carlosDesc: "Gerente · puede asignar, resolver, exportar informes",
    jamieDesc: "Trabajador agrícola · solo lectura",
    inviteRoleManagerDesc: "Puede asignar problemas, marcar como resueltos, exportar informes",
    inviteRoleManager: "Gerente",
    inviteRoleFarmhand: "Trabajador agrícola",
    inviteRoleFarmhandDesc: "Solo lectura — puede ver dispositivos y problemas",
    inviteManagerDesc: "Asignar problemas, marcar resueltos, exportar informes",
    inviteFarmhandDesc: "Solo lectura — ver dispositivos y problemas",
    inviteFillName: "Por favor ingrese su nombre y número de teléfono.",
    invitePickRole: "Por favor seleccione un rol.",
    inviteDemoNote: "El nombre y el teléfono los configuró el dueño de la finca y no se pueden cambiar. Los registros de invitación demo son de solo lectura.",
    emailRequiredForSend: "No hay correo registrado. Agréguelo en Configuración → Cuenta de la finca.",
    emailReportNote: "Generado por AgriGuardian. Descargue el informe PDF completo para más detalles.",
    saved: "Guardado",
    ownerEmailLabel: "Correo para entrega de informes",
    ownerEmailHint: "Se usa al enviar informes de higiene y actividad por correo.",
    pdfActivityTitle: "Registro de Actividad de la Finca",
    pdfWhen: "Cuándo",
    pdfWho: "Quién",
    pdfWhat: "Acción",
    pdfNoActivity: "Aún no se ha registrado actividad.",
    pdfActivityDisclaimer: "Generado por AgriGuardian. Este registro documenta las acciones realizadas dentro de la aplicación — quién hizo qué y cuándo. No rastrea información personal del dispositivo.",
    staleVerifyBadge: "Sin verificar en 6+ meses",
    ownerRole: "Propietario",
    resolveIssuesPerm: "Resolver problemas",
    onlyOwnerTimezone: "Solo el propietario de la finca puede cambiar la zona horaria.",
    tzNote: "Todas las marcas de tiempo en la aplicación reflejarán esta zona horaria independientemente de dónde esté visualizando.",
    cisaDesc: "Verificado automáticamente — no requiere configuración. CISA publica vulnerabilidades activamente explotadas que AgriGuardian verifica contra las marcas de sus dispositivos.",
    vulnDbTitle: "Bases de datos de vulnerabilidades",
    cisaTitle: "Vulnerabilidades conocidas explotadas de CISA",
    loginNamePlaceholder: "p.ej. María García",
    loginFarmPlaceholder: "p.ej. Finca García",
    loginPassPlaceholderHint: "Mín. 8 caracteres",
    loginSigninPassPlaceholder: "Su contraseña",
    loginPhonePlaceholderHint: "(555) 000-0000",
    pwChangedYes: "Sí", pwChangedNo: "No / no estoy seguro",
    supportedLabel: "Con soporte", limitedLabel: "Soporte limitado", unknownLabel: "Desconocido",
    cveFoundLabel: "encontradas",
    signOut: "Cerrar sesión",
    signOutFull: "⏻ Cerrar sesión",
    recommendedAction: "Acción recomendada",
    deviceDetails: "Detalles del dispositivo",
    backToDevices: "Volver a dispositivos",
    resolvedMsg: "Este problema fue marcado como resuelto",
    recActionResolved: "No se requiere acción en este momento — este problema ha sido atendido. Continúe monitoreando y reevalúe si algo cambia.",
    monitorMsg2: "Continúe monitoreando y reevalúe si algo cambia.",
    verifiedMsg: "Este dispositivo parece seguro.",
    tapVerify2: "Toque abajo para verificar que sigue seguro.",
    lastVerifiedOn: "Última verificación",
    resolveTitle: "¿Se resolvió este problema?",
    resolveCheck: "He resuelto este problema",
    saveBtn: "Guardar",
    verifyTodayBtn: "Marcar como verificado hoy",
    resolvedBadgeLabel: "Marcado resuelto:",
    healthWarningText: "Nunca ingrese credenciales de inicio de sesión aquí.",
    saveHealthBtnText: "Guardar verificación",
    healthLastVerified: "Última verificación:",
    sessionWarning: "Sesión expira en",
    staySignedIn: "Continuar sesión", userLabel: "Conectado como:",
    escTitle: "¿No puedes resolverlo tú?",
    escDesc: "Usa esto si el problema no se puede resolver en tu nivel (por ejemplo, equipo al final de su vida útil, requiere aprobación de compra o soporte del proveedor). Se enviará a {target} para que lo gestione — el Propietario será notificado.",
    escReasonLabel: "Motivo de la escalada",
    escReasonPlaceholder: "Selecciona un motivo…",
    escReasons: ["Fin de vida útil — debería retirarse", "Fin de servicio — el fabricante ya no ofrece actualizaciones", "Requiere compra de reemplazo", "Requiere proveedor / distribuidor", "Fuera de mis permisos", "Otro"],
    escNoteLabel: "Detalle para {target} (opcional)",
    escNotePlaceholder: "¿Qué viste y qué necesita decidirse?",
    escSendBtn: "Enviar a {target}",
    escPill: "Requiere acción",
    escBannerTitle: "Enviado a ti — requiere tu decisión",
    escBannerFyiTitle: "Marcado — tu Gerente lo está gestionando",
    escBannerFyiDesc: "Este dispositivo fue escalado a {name}. Puedes monitorear el progreso aquí o intervenir si es necesario.",
    escBannerBy: "Marcado por",
    escBannerOn: "el",
    escBannerReason: "Motivo",
    escBannerNote: "Nota",
    escTakeOwnership: "Asumir responsabilidad",
    escStepInBtn: "Intervenir como Propietario",
    escResolveNow: "Resolver ahora",
    escClearedBadge: "Responsabilidad asumida",
    escDashLabel: "Marcado — requiere acción",
    escFilterNotice: "Mostrando solo los elementos marcados.",
    escClearFilter: "Mostrar todos los dispositivos",
    escSelectReason: "Selecciona un motivo antes de enviar.",
    escAlreadyOpen: "Este elemento ya ha sido escalado.",
  }
};